version: '3'

services:
  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TEST
      MYSQL_USER: User
      MYSQL_PASSWORD: 12345678
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    command:
      bash -c "mysqld --user=root && chmod 644 /etc/mysql/conf.d/my.cnf"
    user: "1000:50"